{{- if .Values.discovery.enabled -}}
{{- $password := (fromYaml (index .Values.milvus.extraConfigFiles "user.yaml")).common.security.defaultRootPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "discoverable-%s" (include "library-chart.fullname" .) | quote }}
  annotations:
    onyxia/discovery: "milvus"
type: Opaque
stringData:
  MILVUS_SERVER_URI: "https://{{ .Values.ingress.hostname }}:443"
  MILVUS_USERNAME: "root"
  MILVUS_PASSWORD: "{{ $password }}"
  MILVUS_TOKEN: "root:{{ $password }}"
{{- end -}}
