apiVersion: v2
name: lakefs
description: Data version control for data lakes.  It enables zero copy isolated environments, and more.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/lakefs.jpg
keyworks:
  - s3
  - git
home: https://lakefs.io/
sources:
  - https://github.com/treeverse/charts/tree/master/charts/lakefs
  - https://github.com/InseeFrLab/helm-charts-databases/tree/master/charts/lakefs
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.50.0
dependencies:
  - name: postgresql
    version: 16.4.14
    repository:  https://charts.bitnami.com/bitnami
    enabled: true
  - name: library-chart
    version: 1.7.14
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
  - name: lakefs
    version: 1.4.3
    repository: https://charts.lakefs.io
    enabled: true
