apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "postgres-cnpg.fullname" . }}
spec:
  name: {{ .Values.auth.database }}
  owner: {{ .Values.auth.username }}
  cluster:
    name: {{ include "postgres-cnpg.fullname" . }}
  {{ if or .Values.extension.pgvector .Values.extension.postgis .Values.extension.pgaudit }}
  extensions:
    {{ if .Values.extension.pgvector }}
    - name: vector
    {{- end }}
    {{ if .Values.extension.pgaudit }}
    - name: pgaudit
    {{- end }}
    {{ if .Values.extension.postgis }}
    - name: postgis
    {{- end }}
  {{- end }}
