global:
  security:
    allowInsecureImages: true
mariadb:
  image:
    tag: "11.5.2"
    repository: bitnamilegacy/mariadb
    pullPolicy: IfNotPresent
  auth:
    rootPassword: ""
    database: my_database
    username: ""
    password: ""
    existingSecret: ""
  volumePermissions:
    enabled: true
    image: 
      repository: bitnamilegacy/os-shell
  primary:
    existingConfigmap: ""
    resources:
      limits: {}
      requests:
        memory: 512Mi
        cpu: 1000m
    service:
      ports:
        mysql: 3306

discovery:
  enabled: true
