apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-catalog
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{- $endpoint   := .Values.s3.endpoint }}
{{- $namespace  := .Release.Namespace }}
{{- $hive       := .Values.discovery.hive }}
{{- $elastic    := .Values.discovery.elastic }}
{{- $opensearch := .Values.discovery.opensearch }}
{{- $mongodb    := .Values.discovery.mongodb }}
{{- $postgres   := .Values.discovery.postgres }}
{{- $username   := .Values.security.username }}
{{- $password   := .Values.security.password }}

{{- range $index, $secret := (lookup "v1" "Secret" $namespace "").items }}
{{- $secretService := index (($secret.metadata).annotations | default dict) "onyxia/discovery" | default "" | toString }}
{{- if $secretService }}

{{- if and $mongodb (eq "mongodb" $secretService) }}
{{- $service  := index $secret.data "mongodb-service" | default "" | b64dec }}
{{- $username := index $secret.data "mongodb-username" | b64dec }}
{{- $password := index $secret.data "mongodb-password" | b64dec }}
{{- $database := index $secret.data "mongodb-database" | b64dec }}
{{- $name     := index $secret.data "mongodb-name" | b64dec }}
{{- $data := dict "service" $service "index" $index "username" $username "password" $password "database" $database "name" $name }}
{{- template "connector.mongodb2" $data }}
{{- end }}

{{- if and $postgres (eq "postgres" $secretService) }}
{{- $service  := index $secret.data "postgres-service" | default "" | b64dec }}
{{- $username := index $secret.data "postgres-username" | b64dec }}
{{- $password := index $secret.data "postgres-password" | b64dec }}
{{- $database := index $secret.data "postgres-database" | b64dec }}
{{- $port     := index $secret.data "postgres-port" }}
{{- $data := dict "service" $service  "index" $index "username" $username "password" $password "database" $database "port" $port }}
{{- template "connector.postgres" $data }}
{{- end }}

{{- if and $hive (eq "hive" $secretService) }}
{{- $service  := index $secret.data "hive-service"  | default "" | b64dec }}
{{- $endpoint := index $secret.data "hive-endpoint" | default "" | b64dec }}
{{- $data := dict "service" $service "index" $index "endpoint" $endpoint }}
{{- template "connector.hive" $data }}
{{- end }}

{{- if and $elastic (eq "elastic" $secretService) }}
{{- $service  := index $secret.data "elastic-service"  | default "" | b64dec }}
{{- $port     := index $secret.data "elastic-port"     | default "" | b64dec }}
{{- $password := index $secret.data "elastic-password" | default "" | b64dec }}
{{- $name     := index $secret.data "elastic-name"     | b64dec }}
{{- $security := index $secret.data "elastic-security" | default "" | b64dec }}
{{- $username := index $secret.data "elastic-username" | default "" | b64dec }}
{{- $tls      := index $secret.data "elastic-tls"      | default "ZmFsc2U=" | b64dec }}
{{- $ignoAddr := index $secret.data "elastic-ignore-publish-address" | default "ZmFsc2U=" | b64dec }}
{{- $schema   := index $secret.data "elastic-schema" | default "ZGVmYXVsdA==" | b64dec }}
{{- $data := dict "service" $service "index" $index "port" $port "password" $password "name" $name "security" $security "username" $username "tls" $tls "ignoreAddress" $ignoAddr "schema" $schema }}
{{- template "connector.elastic" $data }}
{{- end }}

{{- if and $opensearch  (eq "opensearch" $secretService) }}
{{- $service  := index $secret.data "opensearch-service" | default "" | b64dec }}
{{- $port     := index $secret.data "opensearch-port" | default "" | b64dec }}
{{- $password := index $secret.data "opensearch-password" | default "" | b64dec }}
{{- $name     := index $secret.data "opensearch-name" | default "" | b64dec }}
{{- $security := index $secret.data "opensearch-security" | default "" | b64dec }}
{{- $username := index $secret.data "opensearch-username" | default "" | b64dec }}
{{- $tls      := index $secret.data "opensearch-tls" | default "ZmFsc2U=" | b64dec }}
{{- $ignoAddr := index $secret.data "opensearch-ignore-publish-address" | default "ZmFsc2U=" | b64dec }}
{{- $schema   := index $secret.data "opensearch-schema" | default "ZGVmYXVsdA==" | b64dec }}
{{- $data := dict "service" $service  "index" $index "port" $port "password" $password "name" $name "security" $security "username" $username "tls" $tls "ignoreAddress" $ignoAddr "schema" $schema }}
{{- template "connector.opensearch" $data }}
{{- end }}

{{- end }}
{{- end }}

{{- if .Values.catalog.enabled }}
{{- range $catalogName, $catalogProperties := .Values.catalog.additionalCatalogs }}
  {{ $catalogName | lower }}.properties: |
    {{- $relname := $catalogProperties | trim | split " " }}
    {{- range $prop := $relname }}
    {{- $prop | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
