{{- if .Values.discovery.enabled }}
{{- $fullName := include "library-chart.fullname" . -}}
{{- $secretName := printf "%s-%s" "discoverable" $fullName -}}
{{ $namespace:= .Release.Namespace }}
{{ $username:= .Values.security.username }}
{{ $password:= .Values.security.password }}
{{ $hostname:= .Values.ingress.hostname }}
{{ range $index, $secret := (lookup "v1" "Secret" $namespace "").items }}
{{- if (index $secret "metadata" "annotations") }}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "mongodb" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $name:= ( index $secret.data "mongodb-name" | default "") | b64dec  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretName $name}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "%s" $name  | b64enc | quote }}
---
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "postgres" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "postgres-service" | default "") | b64dec  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "%s" $service  | b64enc | quote }}
---
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "hive" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service := ( index $secret.data "hive-service" | default "") | b64dec  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-hive" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "hive"  | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-iceberg" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "iceberg" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-deltalake" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "deltalake" | b64enc | quote }}
---
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "elastic" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "elastic-name" | default "") | b64dec  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "%s" $service  | b64enc | quote }}
---
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "opensearch" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "opensearch-name" | default "") | b64dec  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretName $service}}
  annotations:
    onyxia/discovery: "trino"
type: Opaque
data:
  trino-service: {{ $hostname | b64enc | quote }}
  trino-password: {{ $password | b64enc | quote }}
  trino-username: {{ $username  | b64enc | quote }}
  trino-port: {{ printf "443" | b64enc | quote }}
  trino-database: {{ printf "%s" $service  | b64enc | quote }}
---
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
