{{- if .Values.discovery.enabled }}
{{- $context := . }}
{{- $mongodb    := .Values.discovery.mongodb }}
{{- $postgres   := .Values.discovery.postgres }}
{{- $hive       := .Values.discovery.hive }}
{{- $elastic    := .Values.discovery.elastic }}
{{- $opensearch := .Values.discovery.opensearch }}
{{- range $secret := (lookup "v1" "Secret" .Release.Namespace "").items }}
{{-   $secretService := index (($secret.metadata).annotations | default dict) "onyxia/discovery" | default "" | toString }}
{{-   if and $mongodb (eq "mongodb" $secretService) -}}
{{-     $database := index $secret.data "mongodb-name" | default "" | b64dec -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" $database) -}}
{{-   else if and $postgres (eq "postgres" $secretService) -}}
{{-     $database := index $secret.data "postgres-service" | default "" | b64dec -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" $database) -}}
{{-   else if and $hive (eq "hive" $secretService) -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" "hive") -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" "iceberg") -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" "deltalake") -}}
{{-   else if and $elastic (eq "elastic" $secretService) -}}
{{-     $database := index $secret.data "elastic-name" | default "" | b64dec -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" $database) -}}
{{-   else if and $opensearch (eq "opensearch" $secretService) -}}
{{-     $database := index $secret.data "opensearch-name" | default "" | b64dec -}}
{{-     include "trino.discovery-secret" (dict "context" $context "database" $database) -}}
{{-   end -}}
{{- end -}}
{{- end -}}
