{{- if .Values.discovery.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "discoverable-%s" (include "library-chart.fullname" .) | quote }}
  annotations:
    onyxia/discovery: "chromadb"
type: Opaque
stringData:
  {{- if or (.Values.ingress).enabled (.Values.route).enabled }}
  CHROMA_SERVER_HOST: {{ include "library-chart.service-url" . | quote }}
  {{- if or (.Values.route).enabled (.Values.ingress).tls }}
  CHROMA_SERVER_HTTP_PORT: "443"
  {{- else }}
  CHROMA_SERVER_HTTP_PORT: "80"
  {{- end }}
  {{- else }}
  CHROMA_SERVER_HOST: {{ printf "http://%s" (include "chart.fullname" .Subcharts.chromadb) | quote }}
  CHROMA_SERVER_HTTP_PORT: {{ .Values.chromadb.serverHttpPort | quote }}
  {{- end }}
  {{- if .Values.chromadb.chromadb.auth.enabled }}
  {{- if eq .Values.chromadb.chromadb.auth.type "token" }}
  CHROMA_CLIENT_AUTH_PROVIDER: "chromadb.auth.token_authn.TokenAuthClientProvider"
  {{- else }}
  CHROMA_CLIENT_AUTH_PROVIDER: "chromadb.auth.basic_authn.BasicAuthClientProvider"
  {{- end }}
  CHROMA_AUTH_SECRET: "chromadb-auth"
  {{- end }}
{{- end -}}
