apiVersion: v2
name: kafka
description: Apache Kafka is an event streaming platform for streaming analytics, data integration.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/kafka.png
keywords:
  - streaming
  - messaging
home: https://kafka.apache.org/
sources:
  - https://github.com/InseeFrLab/helm-charts-databases/tree/master/charts/kafka
  - https://github.com/bitnami/charts/tree/master/bitnami/kafka
  - https://github.com/bitnami/bitnami-docker-kafka
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.12

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1"
dependencies:
  - name: kafka
    version: 31.4.0
    repository:  https://charts.bitnami.com/bitnami
  - name: library-chart
    version: 1.5.33
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
