apiVersion: v2
name: postgresql
description: An object-relational database management system, a database server.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/post.png
keywords:
  - SQL
  - Database
home: https://www.postgresql.org/
sources:
  - https://github.com/InseeFrLab/helm-charts-databases/tree/master/charts/postgresql
type: application
version: 1.0.10
appVersion: 17.5.0
dependencies:
- name: postgresql
  version: 16.7.11
  repository:  https://charts.bitnami.com/bitnami
- name: library-chart
  version: 1.7.3
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
