{{- $fullName := include "library-chart.fullname" . -}}
{{- $initContainerName := printf "%s-%s" $fullName "init-data" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.service.image.version }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: cloudbeaver-data
            mountPath: /opt/cloudbeaver/workspace
          {{- end }}
          - name: cb-config
            mountPath: /opt/cloudbeaver/conf/cloudbeaver.conf
            subPath: cloudbeaver.conf
          - name: product-config
            mountPath: /opt/cloudbeaver/conf/product.conf
            subPath: product.conf
          {{- if or .Values.discovery.postgres .Values.discovery.mariadb .Values.discovery.trino  }}
          - name: discovery-secret
            mountPath: /opt/cloudbeaver/conf/initial-data-sources.conf
            subPath: initial-data-sources.conf
          {{- end }}
          env:
          - name: CB_ADMIN_NAME
            value: "{{ .Values.security.username }}"
          - name: CB_ADMIN_PASSWORD
            value: "{{ .Values.security.password }}"
          - name: CB_SERVER_NAME
            value: "{{ .Values.cloudbeaver.serverName }}"
          - name: CB_SERVER_URL
            value: "https://{{ .Values.ingress.hostname }}"
          ports:
            - name: http
              containerPort: {{ .Values.networking.beaver.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: cloudbeaver-data
          persistentVolumeClaim:
            claimName: {{ include "library-chart.fullname" . }}
      {{- end }}
        - name: cb-config
          configMap:
            name: {{ include "library-chart.fullname" . }}-cb-config
        - name: product-config
          configMap:
            name: {{ include "library-chart.fullname" . }}-product-config
        {{- if or .Values.discovery.postgres .Values.discovery.mariadb .Values.discovery.trino }}
        - name: discovery-secret
          secret:
            secretName: {{ include "library-chart.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
